"use client";

import {useEffect,useMemo,useState} from "react";

type Rasi={slug:string;name:string;telugu:string;symbol:string;prediction:string;date:string;source?:string};
const signs=[["aries","మేషం","Mesha Rasi","♈"],["taurus","వృషభం","Vrushabha Rasi","♉"],["gemini","మిథునం","Mithuna Rasi","♊"],["cancer","కర్కాటకం","Karkataka Rasi","♋"],["leo","సింహం","Simha Rasi","♌"],["virgo","కన్య","Kanya Rasi","♍"],["libra","తుల","Tula Rasi","♎"],["scorpio","వృశ్చికం","Vrischika Rasi","♏"],["sagittarius","ధనుస్సు","Dhanus Rasi","♐"],["capricorn","మకరం","Makara Rasi","♑"],["aquarius","కుంభం","Kumbha Rasi","♒"],["pisces","మీనం","Meena Rasi","♓"]];
export default function RasiPhalalu(){
 const [items,setItems]=useState<Rasi[]>([]),[selected,setSelected]=useState("aries"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/rasi-phalalu?lang=te",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.items?.length)throw new Error(j.error||"Today’s Rasi Phalalu are not available yet.");setItems(j.items);setUpdated(j.fetchedAt||new Date().toISOString())}catch(e:any){setError(e?.message||"Unable to load today’s Rasi Phalalu.")}finally{setLoading(false)}};
 useEffect(()=>{load();const id=window.setInterval(load,30*60*1000);return()=>window.clearInterval(id)},[]);
 const active=useMemo(()=>items.find(x=>x.slug===selected),[items,selected]); const sign=signs.find(x=>x[0]===selected)||signs[0];
 return <section className="info"><div className="sectionHead"><div><h2>🔮 రాశి ఫలాలు • Today’s Rasi Phalalu</h2><p className="note">Live daily horoscope feed • updates automatically when fresh data is available.</p></div><button onClick={load} disabled={loading}>{loading?"⟳ Updating…":"↻ Refresh"}</button></div><div className="monthTabs">{signs.map(s=><button key={s[0]} className={selected===s[0]?"active":""} onClick={()=>setSelected(s[0])}>{s[3]} {s[1]}</button>)}</div>{loading&&!items.length?<p>Loading today’s Rasi Phalalu…</p>:active?<article className="tile" style={{minHeight:260}}><div style={{fontSize:42}}>{sign[3]}</div><h2>{active.telugu}</h2><p className="note">{active.name}</p><div style={{whiteSpace:"pre-wrap",lineHeight:1.9,fontSize:17}}>{active.prediction}</div><p className="note">Date: {active.date} • Live source: {active.source||"Vedika Horoscope API"}{updated?" • Synced "+new Date(updated).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):""}</p></article>:<p>{error||"Today’s prediction is not available yet."}</p>}{error&&items.length>0&&<p className="note" role="status">{error}</p>}<p className="note">Rasi Phalalu are traditional horoscope content for devotional/entertainment use. They are not a substitute for professional medical, financial or other advice.</p></section>;
}
