"use client";
import { useEffect, useMemo, useState } from "react";
type Rasi = { slug:string; name:string; telugu:string; symbol:string; prediction:string; date:string; source?:string; sourceUrl?:string; language?: "en"|"te" };
const signs = [["aries","మేషం","Mesha Rasi","♈"],["taurus","వృషభం","Vrushabha Rasi","♉"],["gemini","మిథునం","Mithuna Rasi","♊"],["cancer","కర్కాటకం","Karkataka Rasi","♋"],["leo","సింహం","Simha Rasi","♌"],["virgo","కన్య","Kanya Rasi","♍"],["libra","తుల","Tula Rasi","♎"],["scorpio","వృశ్చికం","Vrischika Rasi","♏"],["sagittarius","ధనుస్సు","Dhanus Rasi","♐"],["capricorn","మకరం","Makara Rasi","♑"],["aquarius","కుంభం","Kumbha Rasi","♒"],["pisces","మీనం","Meena Rasi","♓"]];
export default function RasiPhalalu({ telugu = true }: { telugu?: boolean }) {
 const [items,setItems]=useState<Rasi[]>([]),[selected,setSelected]=useState("aries"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState("");
 const lang=telugu?"te":"en";
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/rasi-phalalu?lang="+lang,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.items?.length)throw new Error(j.error||"Today’s Rasi Phalalu are not available yet.");setItems(j.items);setUpdated(j.fetchedAt||new Date().toISOString())}catch(e:any){setError(e?.message||"Unable to load today’s Rasi Phalalu.")}finally{setLoading(false)}};
 useEffect(()=>{load();const id=window.setInterval(load,30*60*1000);return()=>window.clearInterval(id)},[lang]);
 const active=useMemo(()=>items.find(x=>x.slug===selected),[items,selected]); const sign=signs.find(x=>x[0]===selected)||signs[0];
 return <section className="info"><div className="sectionHead"><div><h2>{telugu?"🔮 రాశి ఫలాలు":"🔮 Daily Rasi Phalalu"}</h2><p className="note">{telugu?"నేటి రాశి ఫలాలు • లైవ్ కంటెంట్ ఫీడ్":"Today’s horoscope • live provider feed"}</p></div><button onClick={load} disabled={loading}>{loading?"⟳ Updating…":"↻ Refresh"}</button></div>
 <div className="monthTabs">{signs.map(s=><button key={s[0]} className={selected===s[0]?"active":""} onClick={()=>setSelected(s[0])}>{s[3]} {telugu?s[1]:s[2]}</button>)}</div>
 {loading&&!items.length?<p>{telugu?"నేటి రాశి ఫలాలు లోడ్ అవుతున్నాయి…":"Loading today’s Rasi Phalalu…"}</p>:active?<article className="tile" style={{minHeight:260}}><div style={{fontSize:42}}>{sign[3]}</div><h2>{telugu?active.telugu:active.name}</h2><p className="note">{active.name}</p><div style={{whiteSpace:"pre-wrap",lineHeight:1.9,fontSize:17}}>{active.prediction}</div><p className="note">{telugu?"తేదీ":"Date"}: {active.date} • {active.source||"Live provider"}{updated?" • "+(telugu?"సింక్ ":"Synced ")+new Date(updated).toLocaleTimeString(telugu?"te-IN":"en-IN",{hour:"2-digit",minute:"2-digit"}):""}</p>{active.sourceUrl&&<a href={active.sourceUrl} target="_blank" rel="noreferrer">{telugu?"సోర్స్ చూడండి":"View source"}</a>}</article>:<p>{error||(telugu?"నేటి రాశి ఫలాలు అందుబాటులో లేవు.":"Today’s prediction is not available yet.")}</p>}
 {error&&items.length>0&&<p className="note" role="status">{error}</p>}<p className="note">{telugu?"ఈ ఫీడ్‌ను సర్వర్ ద్వారా లైవ్‌గా పొందుతాము; పేజీ స్వయంచాలకంగా రిఫ్రెష్ అవుతుంది.":"The feed is fetched server-side and refreshed automatically."}</p></section>;
}