"use client";
import {useEffect,useMemo,useState} from "react";

type Verse={id?:number;verseNumber?:number;text?:string;teluguText?:string;meaning?:string;teluguMeaning?:string;transliteration?:string};
type Chapter={chapterNumber:number;name?:string;nameTranslation?:string;nameMeaning?:string;summary?:string;verses:Verse[]};
const chapters=Array.from({length:18},(_,i)=>i+1);
const ramayana=[["Bala Kanda","బాలకాండ","Rama's birth, childhood and the beginning of his journey."],["Ayodhya Kanda","అయోధ్యకాండ","The exile of Rama and the events surrounding Ayodhya."],["Aranya Kanda","అరణ్యకాండ","Life in the forest and Sita's abduction."],["Kishkindha Kanda","కిష్కింధాకాండ","Rama, Hanuman and the search for Sita."],["Sundara Kanda","సుందరకాండ","Hanuman's journey to Lanka and his meeting with Sita."],["Yuddha Kanda","యుద్ధకాండ","The Lanka campaign and Rama's victory over Ravana."],["Uttara Kanda","ఉత్తరకాండ","The later traditional narrative of Rama's reign and family."]];
export default function ScriptureLibrary({telugu,favorites,onFavorite}:{telugu:boolean;favorites:string[];onFavorite:(key:string)=>void}){
 const [book,setBook]=useState<"gita"|"ramayana">("gita"),[chapter,setChapter]=useState(1),[data,setData]=useState<Chapter|null>(null),[verse,setVerse]=useState(0),[q,setQ]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{if(book!=="gita")return;let live=true;setLoading(true);fetch("/api/scriptures/gita/"+chapter).then(r=>r.json()).then(x=>{if(live){setData(x);setVerse(0)}}).catch(()=>{if(live)setData(null)}).finally(()=>live&&setLoading(false));return()=>{live=false}},[book,chapter]);
 const filtered=useMemo(()=>data?.verses?.map((v,i)=>({v,i})).filter(({v})=>(String(v.verseNumber)+" "+v.text+" "+v.teluguText+" "+v.meaning+" "+v.teluguMeaning).toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
 const current=data?.verses?.[verse];
 return <section className="info" aria-labelledby="scriptures-title">
  <div className="sectionHead"><div><h2 id="scriptures-title">{telugu?"ధర్మ గ్రంథాలయం":"Scripture Library"}</h2><p className="note">{telugu?"భగవద్గీత మరియు వాల్మీకి రామాయణం కోసం అధ్యయన స్థలం.":"Read, search, bookmark and continue your scripture study."}</p></div></div>
  <div className="buttons"><button className={book==="gita"?"active":""} onClick={()=>setBook("gita")}>📖 {telugu?"భగవద్గీత":"Bhagavad Gita"}</button><button className={book==="ramayana"?"active":""} onClick={()=>setBook("ramayana")}>🏹 {telugu?"రామాయణం":"Ramayanam"}</button></div>
  {book==="gita"&&<><div className="formGrid"><label>{telugu?"అధ్యాయం":"Chapter"}<select value={chapter} onChange={e=>setChapter(Number(e.target.value))}>{chapters.map(n=><option key={n} value={n}>{n}. {telugu?"అధ్యాయం":"Chapter"} {n}</option>)}</select></label><label>{telugu?"వెతకండి":"Search"}<input value={q} onChange={e=>setQ(e.target.value)} placeholder={telugu?"శ్లోకం, అర్థం వెతకండి":"Search verse, meaning…"}/></label></div>
  {loading?<p>Loading scripture…</p>:data&&current?<><div className="tile" style={{marginTop:16}}><small>{data.nameTranslation||data.name}</small><h3>{data.chapterNumber}.{current.verseNumber}</h3><p style={{whiteSpace:"pre-wrap",fontSize:18,lineHeight:1.8}}>{current.text}</p>{current.transliteration&&<p className="note" style={{whiteSpace:"pre-wrap"}}>{current.transliteration}</p>}<hr/><p>{telugu?(current.teluguMeaning||current.meaning):current.meaning}</p><div className="buttons"><button onClick={()=>{if(verse>0)setVerse(verse-1)}} disabled={verse===0}>← Previous</button><button onClick={()=>{if(verse<(data.verses.length-1))setVerse(verse+1)}} disabled={verse===data.verses.length-1}>Next →</button><button onClick={()=>onFavorite("gita:"+chapter+":"+current.verseNumber)}>{favorites.includes("gita:"+chapter+":"+current.verseNumber)?"♥ Saved":"♡ Bookmark"}</button><button onClick={()=>{const t=(telugu?(current.teluguMeaning||current.meaning):current.meaning)||current.text||"";if(navigator.share)navigator.share({title:"DharmaPulse — Bhagavad Gita",text:t});else navigator.clipboard?.writeText(t)}}>↗ Share</button></div></div><details style={{marginTop:16}}><summary>{telugu?"శ్లోకాల జాబితా":"Verse list"} ({filtered.length})</summary><div className="grid">{filtered.map(({v,i})=><button className="tile" key={i} onClick={()=>setVerse(i)} style={{textAlign:"left"}}><b>{data.chapterNumber}.{v.verseNumber}</b><small>{(telugu?(v.teluguMeaning||v.meaning):(v.meaning||"")).slice(0,180)}</small></button>)}</div></details></>:<p>Scripture data could not be loaded.</p>}</>}
  {book==="ramayana"&&<><div className="grid" style={{marginTop:16}}>{ramayana.map(([en,te,desc])=><article className="tile" key={en}><span style={{fontSize:28}}>🏹</span><b>{telugu?te:en}</b><small>{desc}</small><div className="buttons"><a href="https://www.gutenberg.org/ebooks/24869" target="_blank" rel="noreferrer">English source ↗</a><a href="https://te.wikisource.org/" target="_blank" rel="noreferrer">Telugu source ↗</a></div></article>)}</div><p className="note" style={{marginTop:16}}>{telugu?"తెలుగు రామాయణానికి పబ్లిక్-డొమైన్ మూలాన్ని ఉపయోగించడానికి ప్రతి సంపుటి హక్కులను స్పష్టంగా నమోదు చేస్తున్నాము.":"The Ramayana reader is structured by all seven Kandas; the bundled English edition and Telugu edition will be added only with verified redistribution rights."}</p></>}
 </section>
}